#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jul  2 11:13:43 2022

@author: darshanpatel
"""

v = 2
type(v)

w = 2.0
type(w)

x = 10j
type(x)

y = "2 Cool for School"
type(y)

z = True
type(z)

A = [v, w, x, y, z]
print(A)

B = "I like pie more than cake"
print(B[0:6])

print(B[7:15])

print(B[16:25])

print(B[0:6], B[11:15], B[21:25])


def multiples(num):
    if num % 15 == 0:
            return "foobar"
    elif num % 5 == 0:
            return "bar"
    elif num % 3 == 0:
            return "foo"
    else:
            return "Not a multiple of 3, 5, or 15"

# Didn't didn't provide headers, description, or examples (-15)
# Example: 

# def foobar(value: int) -> str:
    # """ 
    # This function takes an integer and applies the following rules: 
    # * If it is a multiple of 3 return the string "foo"
    # * If it is a multiple of 5 return the string "bar"
    # * If it is a multiple of 15 return the string "foobar"
    # * If it does not satisfy any of those, return the string "Not a multiple of 3, 5, or 15"
    # >>> foobar(9)
    # "foo"
    # >>> foobar(10)
    # "bar"
    # >>> foobar(45)
    # "foobar"
    # >>> foobar(19)
    # "Not a multiple of 3, 5, or 15"   
    # """
        
number = 240

print(multiples(number))

# Provided one test. Inputting a string breaks code (-5)
multiples(10)
multiples("cat")
multiples(90)
multiples(27)
multiples(101)
