#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jul  6 21:07:55 2022

@author: darshanpatel
"""
import numpy as np

A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

A

A.shape

print(A[1,2])

print(A[0])

print(A[:,1])

print(A[1], A[2])

print(A[1,2], A[1,3], A[2,2], A[2,3])




B = 2**A - 8 # Squared the value instead of multiplying by 2 (-5)
B = 2*A - 8

np.sum(B, axis=1)

np.sum(B, axis=0)

np.cumsum(B, axis=1) # Looking for a single value, so sum of them. This operation transforms current values to their cummulative sum per element (-2)

np.cumsum(B, axis=0) # Looking for a single value, so sum of them. This operation transforms current values to their cummulative sum per element (-2)



np.log(B)

np.sqrt(B)

np.square(B)

np.abs(B)



E1 = np.array([[-20, -1], [40, -1]])

E2= np.array([[-286], [-88]])

Equilibrium= np.dot(np.linalg.inv(E1),E2)

print(Equilibrium) # Which one is equilibrium quantity and which is equilibrium price? (-4)
